### ISSUE TITLE
Works on Mac BUT failed on Ubuntu

### ISSUE THREAD

**Issue by garyyao** [qor/qor#202]
I created sample app basing on QOR admin, it works well on my dev machine (MAC), but failed on server (Ubuntu). Could you pls advice where is the problem, thanks!

I package the binary by command:
env GOOS=linux GOARCH=amd64 go build -v checklist_cms.go

The trace i got in my server:

2017/06/12 10:41:28 Finish [GET] /admin Took 0.08ms
2017/06/12 10:41:28 http: panic serving 175.13.159.151:14969: runtime error: invalid memory address or nil pointer dereference
goroutine 23 [running]:
net/http.(*conn).serve.func1(0xc4200be140)
	/usr/local/Cellar/go/1.8.1/libexec/src/net/http/server.go:1721 +0xd0
panic(0x8a11e0, 0xb850b0)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/panic.go:489 +0x2cf
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.1/libexec/src/html/template/template.go:94 +0x38
html/template.(*Template).Execute(0x0, 0xb5bce0, 0xc420087c00, 0x917860, 0xc420134100, 0x1, 0xc4200cf9b0)
	/usr/local/Cellar/go/1.8.1/libexec/src/html/template/template.go:117 +0x2f
github.com/qor/admin.(*Context).Execute(0xc420134100, 0x91f00d, 0x9, 0x0, 0x0)
	/Users/Gary/GO/ws/src/github.com/qor/admin/context.go:207 +0x2a8
github.com/qor/admin.(*Controller).Dashboard(0xc42009a8f0, 0xc420134100)
	/Users/Gary/GO/ws/src/github.com/qor/admin/controller.go:28 +0x52
github.com/qor/admin.(*Controller).Dashboard-fm(0xc420134100)
	/Users/Gary/GO/ws/src/github.com/qor/admin/route.go:143 +0x34
github.com/qor/admin.(*Admin).NewServeMux.func2(0xc420134100, 0xc42000be60)
	/Users/Gary/GO/ws/src/github.com/qor/admin/route.go:176 +0xe0
github.com/qor/admin.Middleware.Next(0x91febf, 0xa, 0xc42009aa50, 0xc42000be60, 0xc420134100)
	/Users/Gary/GO/ws/src/github.com/qor/admin/route.go:37 +0x48
github.com/qor/admin.(*Admin).NewServeMux.func1(0xc420134100, 0xc42000be20)
	/Users/Gary/GO/ws/src/github.com/qor/admin/route.go:166 +0xb5
github.com/qor/admin.Middleware.Next(0x92c3d5, 0x1c, 0x960610, 0xc42000be20, 0xc420134100)
	/Users/Gary/GO/ws/src/github.com/qor/admin/route.go:37 +0x48
github.com/qor/admin.Admin.registerCompositePrimaryKeyCallback.func1(0xc420134100, 0xc4203e64a0)
	/Users/Gary/GO/ws/src/github.com/qor/admin/composite_primary_key_callback.go:27 +0x1a3
github.com/qor/admin.(*serveMux).ServeHTTP(0xc42000c620, 0xb60120, 0xc420087c00, 0xc420121000)
	/Users/Gary/GO/ws/src/github.com/qor/admin/route.go:399 +0x518
net/http.(*ServeMux).ServeHTTP(0xc4200a18f0, 0xb60120, 0xc420087c00, 0xc420121000)
	/usr/local/Cellar/go/1.8.1/libexec/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc420241ce0, 0xb60120, 0xc420087c00, 0xc420121000)
	/usr/local/Cellar/go/1.8.1/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4200be140, 0xb60860, 0xc42003eb40)
	/usr/local/Cellar/go/1.8.1/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8.1/libexec/src/net/http/server.go:2668 +0x2ce

**Comment by pedrokoblitz** [comment]
I've had the exact same issue. After some debugging, I've noticed the admin/composite_primary_keys.go is generating indexes with same name, probably due to empty strings being passed as parameters. If I can find a workaround I'll submit a pull request in the next couple of days.

**Comment by jinzhu** [comment]
@garyyao could you submit a simple example that will fail, I can't reproduce this issue... but I guess this is caused by failed to find template, are you using bindatafs? 

@pedrokoblitz are you talking about the same issue?

**Comment by pedrokoblitz** [comment]
Yes, same issue. I commented out the content of both functions inside the composite_primary_keys file and it worked fine.

"An example that will fail" is Qor on Ubuntu. When running any simple example, main.go will start the server. The root "/" will output the standard "Not found" message. But when trying to access "/admin" the server redirects back to "/" and the console output is what @garyyao pasted above.

Again: the issue is on the composite primary keys file. No bindatafs in my case

 Similar case with the qor-example repo. The seeds return a couple of "duplicate index" messages. The front page renders but no products and broken links.

**Comment by pedrokoblitz** [comment]
Also: I'm sort of new to both QOR and GORM. I was looking at gorm docs now and thinking; I dont have composite primary keys in my data model. I wonder if that's what is confusing the compiler. Maybe it expects it and returns error when it doesnt find any. Tomorrow I'm going to try to build some models with composite PKs and see if it works.

Still puzzled why it works on Mac. Always puzzled why people buy apple products, but that's a whole different puzzle. =D

**Comment by iliyav** [comment]
I have the same issue. The binary for linux panics with above mentioned stacktrace. I tried on fresh ubuntu 16.04, in docker container.
At the same time, binary for mac works fine.

**Comment by pedrokoblitz** [comment]
Follow up. I was on vacation when I had the issue on Ubuntu. This week I went back to work. My home Ubuntu is 14.04. At work, I use 16.04. I haven't checked if there were any updates, but it worked with no issues on 16.04.

**Comment by iliyav** [comment]
I figured out that the issue is not connected to OS. I added compiling of qor admin templates with bindatafs, and now it works fine on Ubuntu.

**Comment by andrioid** [comment]
@iliyav Can you remember what you did to get this working?

**Comment by ZetaChow** [comment]
similar #240  solved
