### ISSUE TITLE
rich_editor  medialibrary   no responding

### ISSUE THREAD

**Issue by owengaozhen** [qor/qor#232]
```
news.Meta(&admin.Meta{
		Name: "Body",
		Type: "rich_editor",
		Config: &admin.RichEditorConfig{
			AssetManager: ctrl.AssetManager,
			Plugins: []admin.RedactorPlugin{
				{Name: "medialibrary", Source: "/admin/assets/javascripts/qor_redactor_medialibrary/qor_redactor_medialibrary.js"},
				{Name: "alignment", Source: "/admin/assets/javascripts/qor_redactor_alignment.js"},
				{Name: "inlinestyle", Source: "/static/plugins/inlinestyle.js"},
			},
		},
	})
```

**Comment by azumads** [comment]
/* ********************************* Usage in qor-example:
product.Meta(&admin.Meta{Name: "Description", Config: &admin.RichEditorConfig{AssetManager: assetManager,
    Plugins: []admin.RedactorPlugin{
        {Name: "medialibrary", Source: "/admin/assets/javascripts/qor_redactor_medialibrary.js"},
        {Name: "loadstyle", Source: "/admin/assets/javascripts/qor_redactor_loadstyle.js"},
    },
    Settings: map[string]interface{}{
        "medialibraryUrl": "/admin/product_images",
        "loadStyleNamespace": "yourNamespace",
        "loadStyleLink": "http://your_stylesheets_file_path",
    }
}})
********************************* */

**Comment by azumads** [comment]
You need to have a Media Library first.
https://github.com/qor/media/blob/master/media_library/media_library.go

**Comment by owengaozhen** [comment]
yes . 
I have a media library on  admin
```
type Cms struct {
	media_library.MediaLibrary
	Catelog  string
	Code     string
	FileType string
}
```
![image](https://user-images.githubusercontent.com/8510542/43446930-bd5b1b5c-94dc-11e8-9654-9674d870b268.png)

**Comment by azumads** [comment]
"medialibraryUrl": "/admin/product_images"

**Comment by owengaozhen** [comment]
????

**Comment by owengaozhen** [comment]
what if i got 2 media library, how can I config both of them?

**Comment by azumads** [comment]
Yes, you can 

richEditorConfig := &admin.RichEditorConfig{
		Plugins: []admin.RedactorPlugin{
			{Name: "medialibrary1", Source: "/admin/assets/javascripts/qor_redactor_medialibrary.js"},
			{Name: "medialibrary2", Source: "XXXXXXXXXXXX"},
		},
		Settings: map[string]interface{}{
			"replaceDivs":        false,
			"cleanSpaces":        false,
			"loadStyleNamespace": "asics_product_integration",
			"medialibraryUrl":    "/admin/media_library/",
			"medialibraryUrl2":      "XXXXXXXX",
		},
	}

**Comment by owengaozhen** [comment]
```

/usr/local/lib/go/src/text/template/exec.go:432
/usr/local/lib/go/src/text/template/exec.go:535
/usr/local/lib/go/src/text/template/exec.go:667
/usr/local/lib/go/src/reflect/value.go:308
/usr/local/lib/go/src/reflect/value.go:447
/usr/local/lib/go/src/runtime/asm_amd64.s:574
/home/owen/go/src/github.com/qor/admin/func_map.go:89
/home/owen/go/src/github.com/qor/admin/func_map.go:459
/home/owen/go/src/github.com/qor/admin/func_map.go:475
/home/owen/go/src/github.com/qor/admin/func_map.go:646
got error when render form template for Localization(localization): haven't found form template for meta Localization
goroutine 1233 [running]:

```

```
Config: &admin.RichEditorConfig{
			AssetManager: ctrl.AssetManager,
			Plugins: []admin.RedactorPlugin{
				{Name: "medialibrary", Source: "/admin/assets/javascripts/qor_redactor_medialibrary/qor_redactor_medialibrary.js"},
				{Name: "medialibrary2", Source: "/admin/assets/javascripts/qor_redactor_test_medialibrary.js"},
				{Name: "alignment", Source: "/admin/assets/javascripts/qor_redactor_alignment.js"},
				{Name: "inlinestyle", Source: "/static/plugins/inlinestyle.js"},
			},
			Settings: map[string]interface{}{
				"replaceDivs": false,
				"cleanSpaces": false,
				"loadStyleNamespace": "asics_product_integration",
				"medialibraryUrl": "/admin/cmsben-di-su-cai",
				"medialibrary2Url": "/admin/yun-di-su-cai",

			},
		},
```

**Comment by owengaozhen** [comment]
can you help me??

**Comment by azumads** [comment]
Have no idea, it's seems https://github.com/qor/l10n problem

**Comment by owengaozhen** [comment]
qor_redactor_test_medialibrary.js  
I modified the mediaboxUrl.
Wonder if this should work
```
addMedialibrary: function() {
            var $element = this.$element,
                data = {selectModal: 'mediabox', maxItem: '1'},
                mediaboxUrl = $element.data().redactorSettings.medialibrary2Url,
                BottomSheets;

            this.medialibrary.BottomSheets = BottomSheets = $('body').data('qor.bottomsheets');
            data.url = mediaboxUrl;
            BottomSheets.open(data, this.medialibrary.handleMediaLibrary);
        },
```

**Comment by owengaozhen** [comment]
error return:
```
runtime/debug.Stack(0x266, 0x0, 0x0)
        /usr/local/lib/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/lib/go/src/runtime/debug/stack.go:16 +0x22
github.com/qor/qor/utils.ExitWithMsg(0xc9c7e0, 0xc421407cf0, 0x0, 0x0, 0x0)
        /home/owen/go/src/github.com/qor/qor/utils/utils.go:226 +0x146
github.com/qor/admin.(*Context).renderMeta(0xc42016d110, 0xc4207c7860, 0xd0fa60, 0xc4211f2000, 0xc4203c19c0, 0x2, 0x2, 0xdfdd4b, 0x4, 0xc4202ed6c0)
        /home/owen/go/src/github.com/qor/admin/func_map.go:646 +0x9bd
github.com/qor/admin.(*Context).renderSections(0xc42016d110, 0xd0fa60, 0xc4211f2000, 0xc420199280, 0xf, 0x10, 0xc42120c3e0, 0x1, 0x1, 0xc4202492d0, ...)
        /home/owen/go/src/github.com/qor/admin/func_map.go:475 +0x124
github.com/qor/admin.(*Context).renderForm(0xc42016d110, 0xd0fa60, 0xc4211f2000, 0xc420199280, 0xf, 0x10, 0xc4213ca178, 0x412c6c)
        /home/owen/go/src/github.com/qor/admin/func_map.go:459 +0x164
github.com/qor/admin.(*Context).(github.com/qor/admin.renderForm)-fm(0xd0fa60, 0xc4211f2000, 0xc420199280, 0xf, 0x10, 0x0, 0x0)
        /home/owen/go/src/github.com/qor/admin/func_map.go:89 +0x5c
reflect.Value.call(0xcc3f40, 0xc4211a03b0, 0x13, 0xdfd8c7, 0x4, 0xc420ec69c0, 0x2, 0x2, 0xdf58e0, 0x1, ...)
        /usr/local/lib/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xcc3f40, 0xc4211a03b0, 0x13, 0xc420ec69c0, 0x2, 0x2, 0xeed600, 0xc421345b90, 0xc8a3a0)
        /usr/local/lib/go/src/reflect/value.go:308 +0xa4
text/template.(*state).evalCall(0xc4213caaf0, 0xdf7880, 0xc42016d110, 0x16, 0xcc3f40, 0xc4211a03b0, 0x13, 0xeed540, 0xc421345b00, 0xc4214d09ab, ...)
        /usr/local/lib/go/src/text/template/exec.go:667 +0x4f1
text/template.(*state).evalFunction(0xc4213caaf0, 0xdf7880, 0xc42016d110, 0x16, 0xc421345b30, 0xeed540, 0xc421345b00, 0xc4206fa840, 0x3, 0x4, ...)
        /usr/local/lib/go/src/text/template/exec.go:535 +0x176
text/template.(*state).evalCommand(0xc4213caaf0, 0xdf7880, 0xc42016d110, 0x16, 0xc421345b00, 0x0, 0x0, 0x0, 0x0, 0xc4213ca970, ...)
        /usr/local/lib/go/src/text/template/exec.go:432 +0x516
text/template.(*state).evalPipeline(0xc4213caaf0, 0xdf7880, 0xc42016d110, 0x16, 0xc4203679a0, 0x0, 0x0, 0x98)
        /usr/local/lib/go/src/text/template/exec.go:405 +0x10f
text/template.(*state).walk(0xc4213caaf0, 0xdf7880, 0xc42016d110, 0x16, 0xeed440, 0xc421345bc0)
        /usr/local/lib/go/src/text/template/exec.go:231 +0x4a5
text/template.(*state).walk(0xc4213caaf0, 0xdf7880, 0xc42016d110, 0x16, 0xeed680, 0xc421345590)
        /usr/local/lib/go/src/text/template/exec.go:239 +0x11d
text/template.(*Template).execute(0xc4206fa600, 0xee46e0, 0xc42016d1f0, 0xdf7880, 0xc42016d110, 0x0, 0x0)
        /usr/local/lib/go/src/text/template/exec.go:194 +0x1e6
text/template.(*Template).Execute(0xc4206fa600, 0xee46e0, 0xc42016d1f0, 0xdf7880, 0xc42016d110, 0x0, 0xc42000e510)
        /usr/local/lib/go/src/text/template/exec.go:177 +0x53
html/template.(*Template).Execute(0xc421345500, 0xee46e0, 0xc42016d1f0, 0xdf7880, 0xc42016d110, 0x0, 0xc4213cac38)
        /usr/local/lib/go/src/html/template/template.go:122 +0x8c
github.com/qor/admin.(*Context).renderText(0xc42016d110, 0xc4214d0800, 0x3e9, 0xdf7880, 0xc42016d110, 0x3e9, 0x5e9)
        /home/owen/go/src/github.com/qor/admin/context.go:159 +0x168
github.com/qor/admin.(*Context).renderWith(0xc42016d110, 0xdfdcf7, 0x4, 0xdf7880, 0xc42016d110, 0xc4200297f0, 0xf)
        /home/owen/go/src/github.com/qor/admin/context.go:175 +0x15b
github.com/qor/admin.(*Context).Render(0xc420185500, 0xdfdcf7, 0x4, 0xc4213cada0, 0x1, 0x1, 0x0, 0x0)
        /home/owen/go/src/github.com/qor/admin/context.go:194 +0x1c9
github.com/qor/admin.(*Context).Execute(0xc420185500, 0xdfdcf7, 0x4, 0xd0fa60, 0xc4211f2000)
        /home/owen/go/src/github.com/qor/admin/context.go:226 +0x1cc
github.com/qor/admin.(*Controller).Show.func1()
        /home/owen/go/src/github.com/qor/admin/controller.go:130 +0x51
github.com/qor/responder.(*Responder).Respond(0xc420e476d0, 0xc420427400)
        /home/owen/go/src/github.com/qor/responder/responder.go:77 +0x1d0
github.com/qor/admin.(*Controller).Show(0xc420456630, 0xc420185500)
        /home/owen/go/src/github.com/qor/admin/controller.go:133 +0x27a
github.com/qor/admin.(*Controller).Show-fm(0xc420185500)
        /home/owen/go/src/github.com/qor/admin/route.go:307 +0x34
github.com/qor/admin.(*Admin).NewServeMux.func2(0xc420185500, 0xc4201efde0)
        /home/owen/go/src/github.com/qor/admin/route.go:176 +0xe0
github.com/qor/admin.Middleware.Next(0xe0443a, 0xa, 0xc421498670, 0xc4201efde0, 0xc420185500)
        /home/owen/go/src/github.com/qor/admin/route.go:37 +0x48
github.com/qor/admin.(*Admin).NewServeMux.func1(0xc420185500, 0xc4201efdc0)
        /home/owen/go/src/github.com/qor/admin/route.go:166 +0xa1
github.com/qor/admin.Middleware.Next(0xe02990, 0x8, 0xe58e40, 0xc4201efdc0, 0xc420185500)
        /home/owen/go/src/github.com/qor/admin/route.go:37 +0x48
github.com/qor/publish2.Publish.ConfigureQorResourceBeforeInitialize.func3(0xc420185500, 0xc420ea2340)
        /home/owen/go/src/github.com/qor/publish2/publish2.go:376 +0x470
github.com/qor/admin.Middleware.Next(0xe08e0c, 0xf, 0xe58dc8, 0xc420ea2340, 0xc420185500)
        /home/owen/go/src/github.com/qor/admin/route.go:37 +0x48
github.com/qor/l10n.(*Locale).ConfigureQorResource.func7(0xc420185500, 0xc421027320)
        /home/owen/go/src/github.com/qor/l10n/l10n.go:248 +0x6e2
github.com/qor/admin.Middleware.Next(0xe14b33, 0x1c, 0xe58c70, 0xc421027320, 0xc420185500)
        /home/owen/go/src/github.com/qor/admin/route.go:37 +0x48
github.com/qor/admin.Admin.registerCompositePrimaryKeyCallback.func1(0xc420185500, 0xc4201892e0)
        /home/owen/go/src/github.com/qor/admin/composite_primary_key_callback.go:27 +0x208
github.com/qor/admin.(*serveMux).ServeHTTP(0xc4200aeb70, 0xeeb700, 0xc4203f62a0, 0xc420427400)
        /home/owen/go/src/github.com/qor/admin/route.go:267 +0x575
net/http.(*ServeMux).ServeHTTP(0xc420dbd350, 0xeeb700, 0xc4203f62a0, 0xc420427400)
        /usr/local/lib/go/src/net/http/server.go:2337 +0x130
github.com/qor/redirect_back.(*RedirectBack).Middleware.func1(0xeeb700, 0xc4203f62a0, 0xc420427400)
        /home/owen/go/src/github.com/qor/redirect_back/redirect_back.go:139 +0x1fa
net/http.HandlerFunc.ServeHTTP(0xc4201efe20, 0xeeb700, 0xc4203f62a0, 0xc420427300)
        /usr/local/lib/go/src/net/http/server.go:1947 +0x44
github.com/qor/session/gorilla.Gorilla.Middleware.func1(0xeeb700, 0xc4203f62a0, 0xc420427200)
        /home/owen/go/src/github.com/qor/session/gorilla/gorilla.go:125 +0x123
net/http.HandlerFunc.ServeHTTP(0xc4201efe40, 0xeeb700, 0xc4203f62a0, 0xc420427200)
        /usr/local/lib/go/src/net/http/server.go:1947 +0x44
net/http.serverHandler.ServeHTTP(0xc421394340, 0xeeb700, 0xc4203f62a0, 0xc420427200)
        /usr/local/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4202e8960, 0xeec4c0, 0xc420790000)
        /usr/local/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/local/lib/go/src/net/http/server.go:2795 +0x27b

```

**Comment by azumads** [comment]
seem you don't use latest qor

**Comment by owengaozhen** [comment]
All of me are the latest
![image](https://user-images.githubusercontent.com/8510542/43499390-c94ce9f8-957d-11e8-8a19-3cdc4fb6bc3d.png)

**Comment by azumads** [comment]
https://github.com/qor/admin/blob/master/func_map.go#L646

The error lines don't match the latest master

**Comment by owengaozhen** [comment]
yes.I submitted a pr:
https://github.com/qor/admin/pull/144
But you don't have a merger

**Comment by owengaozhen** [comment]
@azumads ccan you help me ?

**Comment by azumads** [comment]
your description is so vague, so can't give constructive advice.

**Comment by owengaozhen** [comment]
data:
![image](https://user-images.githubusercontent.com/8510542/43561861-a68a031e-964b-11e8-98ef-2c44ecf7aa3e.png)
line:54   mediaOption==undefined

**Comment by owengaozhen** [comment]
@azumads

**Comment by arundudeemmt** [comment]
please can you write what is exact issue you facing and error you faced .We are using qor quite extensively for media as well and so far faced no issue .Only feature set it lacks is bulk upload of images but we build our own for same .
@rohit-nahata (https://github.com/rohit-nahata) is QOR champion you can tag him for any help

**Comment by owengaozhen** [comment]
@arundudeemmt @azumads SelectType data is empty.

**Comment by rohit-nahata** [comment]
@owengaozhen the SelectedType value doesn't get stored in db since it is a hidden field. You need to set it using your own setter and getter for selected type.
 I solved it by using the meta processor (same as in media library) and defining setter and getter for Selected type.
Not sure if it was the right approach but worked for me.

**Comment by owengaozhen** [comment]
yes,SelectedType is hidden field,but Even if I set selected_type equal to image, there is no effect.
![image](https://user-images.githubusercontent.com/8510542/44502118-8fba0800-a6c2-11e8-837e-497e66f97cb3.png)

**Comment by owengaozhen** [comment]
@rohit-nahata

**Comment by rohit-nahata** [comment]
@owengaozhen the selected_type field is picked from the File column. Just check the json in your file column.
Example:
{"FileName":"Image_3.jpeg","Url":"/system/product_media/5/image_3.20180729183018585034607.jpeg.jpeg","Video":"",**"SelectedType":"image",**"Description":"Adding Description again in edit mode again"}

**Comment by owengaozhen** [comment]
file cloumn json:
```
{"FileName":"1.png","Url":"//tets-1252882253.cos.ap-shanghai.myqcloud.com/system/cms/2/file.png","Video":"","SelectedType":"","Description":""}
```

**Comment by owengaozhen** [comment]
@rohit-nahata  yes, select type eq undefined,
eg:
![image](https://user-images.githubusercontent.com/8510542/44508329-77f17c80-a6e0-11e8-9ddd-c85ac65dde55.png)

**Comment by rohit-nahata** [comment]
@owengaozhen so as I mentioned above, you need to set the selected type value using processor. The logic is available in media library of QOR.
I used the entire logic in my code to make it work.

**Comment by owengaozhen** [comment]
@rohit-nahata the selectedType is still empty when I use `media_library.MediaLibrary{}`, Could you give me an example for how to do this?
![image](https://user-images.githubusercontent.com/8510542/44562306-982a4580-a78b-11e8-9188-e0645ffeefc3.png)

**Comment by rohit-nahata** [comment]
@owengaozhen this is the code snippet from media library.
productMediaResource.AddProcessor(&resource.Processor{
		Name: "media-library-processor",
		Handler: func(record interface{}, metaValues *resource.MetaValues, context *qor.Context) error {
			if mediaLibrary, ok := record.(media_library.MediaLibraryInterface); ok {
				var filename string
				var mediaOption media_library.MediaOption

				for _, metaValue := range metaValues.Values {
					if fileHeaders, ok := metaValue.Value.([]*multipart.FileHeader); ok {
						for _, fileHeader := range fileHeaders {
							filename = fileHeader.Filename
						}
					}
				}

				if metaValue := metaValues.Get("MediaOption"); metaValue != nil {
					mediaOptionStr := utils.ToString(metaValue.Value)
					json.Unmarshal([]byte(mediaOptionStr), &mediaOption)
				}

				if mediaOption.SelectedType == "video_link" {
					mediaLibrary.SetSelectedType("video_link")
				} else if filename != "" {
					if media.IsImageFormat(filename) {
						mediaLibrary.SetSelectedType("image")
					} else if media.IsVideoFormat(filename) {
						mediaLibrary.SetSelectedType("video")
					} else {
						mediaLibrary.SetSelectedType("file")
					}
				}
			}
			return nil
		},
	})
I used the same code in my file and functions as well.
Thats why I said, this might not be right approach but worked for me.

**Comment by owengaozhen** [comment]
I have added the processor on the admin resource, but still get the empty selectedType and mediaOption.
```
news.Meta(&admin.Meta{
		Name: "Body",
		Type: "rich_editor",
		Config: &admin.RichEditorConfig{
			AssetManager: ctrl.AssetManager,
			Plugins: []admin.RedactorPlugin{
				{Name: "medialibrary", Source: "/admin/assets/javascripts/qor_redactor_medialibrary/qor_redactor_medialibrary.js"},
				//{Name: "medialibrary2", Source: "/admin/assets/javascripts/qor_redactor_test_medialibrary.js"},
				{Name: "alignment", Source: "/admin/assets/javascripts/qor_redactor_alignment.js"},
				{Name: "inlinestyle", Source: "/static/plugins/inlinestyle.js"},
			},
			Settings: map[string]interface{}{
				//"replaceDivs": false,
				//"cleanSpaces": false,
				//"loadStyleNamespace": "asics_product_integration",
				"medialibraryUrl": "/admin/cmsben-di-su-cai",
				//"medialibrary2Url": "/admin/yun-pan-su-cai",

			},
		},
	})
	news.AddProcessor(&resource.Processor{
		Name: "media-library-processor",
		Handler: func(record interface{}, metaValues *resource.MetaValues, context *qor.Context) error {
			fmt.Println("--------start---------")

			fmt.Println(record)
			if mediaLibrary, ok := record.(media_library.MediaLibraryInterface); ok {
				var filename string
				var mediaOption media_library.MediaOption

				for _, metaValue := range metaValues.Values {
					if fileHeaders, ok := metaValue.Value.([]*multipart.FileHeader); ok {
						for _, fileHeader := range fileHeaders {
							filename = fileHeader.Filename
						}
					}
				}

				if metaValue := metaValues.Get("MediaOption"); metaValue != nil {
					mediaOptionStr := utils.ToString(metaValue.Value)
					json.Unmarshal([]byte(mediaOptionStr), &mediaOption)
				}

				if mediaOption.SelectedType == "video_link" {
					mediaLibrary.SetSelectedType("video_link")
				} else if filename != "" {
					if media.IsImageFormat(filename) {
						mediaLibrary.SetSelectedType("image")
					} else if media.IsVideoFormat(filename) {
						mediaLibrary.SetSelectedType("video")
					} else {
						mediaLibrary.SetSelectedType("file")
					}
				}
			}else {
				fmt.Println("--------else---------")
			}
			return nil
		},
	})
```

The added processor does not even invoked when I pull the trigger.

**Comment by owengaozhen** [comment]
From the setting `"medialibraryUrl": "/admin/cmsben-di-su-cai",`

The struct of my media library as below:
```
type Cms struct {
	media_library.MediaLibrary
	Catelog  string
	Code     string
	FileType string
}
```

**Comment by owengaozhen** [comment]
@rohit-nahata no effects;
```
type Cms struct {
	media_library.MediaLibrary
	Catelog  string
	Code     string
	FileType string
}

func (productImage *Cms) SetSelectedType(typ string) {
	productImage.SelectedType = typ
}

func (productImage *Cms) GetSelectedType() string {
	return productImage.SelectedType
}

func (productImage *Cms) ScanMediaOptions(mediaOption media_library.MediaOption) error {
	fmt.Println("Inside scanned media option")

	if bytes, err := json.Marshal(mediaOption); err == nil {
		return productImage.File.Scan(bytes)
	} else {
		return err
	}
}

func (productImage *Cms) GetMediaOption() (mediaOption media_library.MediaOption) {

	mediaOption.Video = productImage.File.Video
	mediaOption.FileName = productImage.File.FileName
	mediaOption.URL = productImage.File.URL()
	mediaOption.OriginalURL = productImage.File.URL("original")
	mediaOption.CropOptions = productImage.File.CropOptions
	mediaOption.Sizes = productImage.File.GetSizes()
	mediaOption.Description = productImage.File.Description

	return
}

```

```
cmsRes := ctrl.QorConfig.QorAdmin.AddResource(&Cms{}, &admin.Config{
		Permission: roles.Allow(roles.Read, helpers.CmsAdmin, getRole(localResourceRole, roleRead)).
			Allow(roles.Update, helpers.CmsAdmin, getRole(localResourceRole, roleEdit)).
			Allow(roles.Delete, helpers.CmsAdmin, getRole(localResourceRole, roleDelete)).
			Allow(roles.Create, helpers.CmsAdmin, getRole(localResourceRole, roleAdd)),
		Menu: []string{"管理"}, IconName: "computer", Name: "cms本地素材"})
	cmsRes.AddProcessor(&resource.Processor{
		Name: "media-library-processor",
		Handler: func(record interface{}, metaValues *resource.MetaValues, context *qor.Context) error {
			fmt.Println("--------start---------")

			fmt.Println(record)
			if mediaLibrary, ok := record.(media_library.MediaLibraryInterface); ok {
				var filename string
				var mediaOption media_library.MediaOption

				for _, metaValue := range metaValues.Values {
					if fileHeaders, ok := metaValue.Value.([]*multipart.FileHeader); ok {
						for _, fileHeader := range fileHeaders {
							filename = fileHeader.Filename
						}
					}
				}

				if metaValue := metaValues.Get("MediaOption"); metaValue != nil {
					mediaOptionStr := utils.ToString(metaValue.Value)
					json.Unmarshal([]byte(mediaOptionStr), &mediaOption)
				}

				if mediaOption.SelectedType == "video_link" {
					mediaLibrary.SetSelectedType("video_link")
				} else if filename != "" {
					if media.IsImageFormat(filename) {
						mediaLibrary.SetSelectedType("image")
					} else if media.IsVideoFormat(filename) {
						mediaLibrary.SetSelectedType("video")
					} else {
						mediaLibrary.SetSelectedType("file")
					}
				}
			}else {
				fmt.Println("--------else---------")
			}
			return nil
		},
	})
```

**Comment by owengaozhen** [comment]
@rohit-nahata can you help me?

**Comment by rohit-nahata** [comment]
@owengaozhen I implemented it in the following way. Can you try it once on similar lines?
Product Media Model:
type ProductMedia struct {
	gorm.Model
	Title        string
	ProductID    uint
	Priority     uint
	Description string `gorm:"type:text"`
	SelectedType string
	ImageTag     string                            `gorm:"type:enum('main','what_to_expect','cover')"`
	File         oss.OSS `sql:"size:4294967295;" media_library:"url:/system/{{class}}/{{primary_key}}/{{filename_with_hash}}"`
	IsActive     bool `gorm:"not null" sql:"index" default:"true"`
}

func (productMedia *ProductMedia) SetSelectedType(typ string) {
	productMedia.SelectedType = typ

}

func (productMedia *ProductMedia) GetSelectedType() string {
	return productMedia.SelectedType
}


Processor code :
productMediaResource.AddProcessor(&resource.Processor{
		Name: "media-library-processor",
		Handler: func(record interface{}, metaValues *resource.MetaValues, context *qor.Context) error {
				var filename string
				fileType := record.(*models.ProductMedia)
				for _, metaValue := range metaValues.Values {
					if fileHeaders, ok := metaValue.Value.([]*multipart.FileHeader); ok {
						for _, fileHeader := range fileHeaders {
							filename = fileHeader.Filename
						}
					}
				}
				//Set the value of Selected type - image or video
					if media.IsImageFormat(filename) {
						fileType.SetSelectedType(C.FILETYPE_IMAGE)
					} else if media.IsVideoFormat(filename) {
						fileType.SetSelectedType(C.FILETYPE_VIDEO)
					} else {
						return validations.NewError(record,C.Product_Media_File,"File format not supported")
					}
			return nil
		},
	})
I am using it this way to store mdeia files.

**Comment by owengaozhen** [comment]
@rohit-nahata no effects;
```

type Cms struct {
	gorm.Model
	Catelog      string
	Code         string
	FileType     string
	SelectedType string
	File         oss.OSS `sql:"size:4294967295;" media_library:"url:/system/{{class}}/{{primary_key}}/{{filename_with_hash}}"`
}

func (productImage *Cms) SetSelectedType(typ string) {
	productImage.SelectedType = typ
}

func (productImage *Cms) GetSelectedType() string {
	return productImage.SelectedType
}
cmsRes.AddProcessor(&resource.Processor{
		Name: "media-library-processor",
		Handler: func(record interface{}, metaValues *resource.MetaValues, context *qor.Context) error {
			var filename string
			fileType := record.(*Cms)
			for _, metaValue := range metaValues.Values {
				if fileHeaders, ok := metaValue.Value.([]*multipart.FileHeader); ok {
					for _, fileHeader := range fileHeaders {
						filename = fileHeader.Filename
					}
				}
			}
			//Set the value of Selected type - image or video
			if media.IsImageFormat(filename) {
				fileType.SetSelectedType("image")
			} else if media.IsVideoFormat(filename) {
				fileType.SetSelectedType("video")
			} else {
				return validations.NewError(record, "file", "File format not supported")
			}
			return nil
		},
	})

```

**Comment by bullnames** [comment]
After testing, adding the MainImage field to the model can be solved

type Product struct {
	gorm.Model
	Name                  string
	NameWithSlug          slug.Slug `l10n:"sync"`
	MainImage             media_library.MediaBox
	Description           string           `sql:"size:2000"`

}
