### ISSUE TITLE
Get start documentation is trash

### ISSUE THREAD

**Issue by AndreiD** [qor/qor#246]
So I heard some company is using this so I come to take a look.
You have nice stars on github....mmm ok, let's see "Get Started"

the first thing that you do is copy paste the main.go file
and that file has 

"github.com/qor/qor"

unused import! so from the start the compiler will complain.

removing it gives

~~~~
2019/05/28 11:27:16 http: panic serving [::1]:43480: runtime error: invalid memory address or nil pointer dereference
goroutine 8 [running]:
net/http.(*conn).serve.func1(0xc00017c000)
        /home/me/.go/src/net/http/server.go:1769 +0x139
panic(0x9e81e0, 0xef8030)
        /home/me/.go/src/runtime/panic.go:522 +0x1b5
~~~~

importing it for sides effects just starts and ends the server

**Comment by decker502** [comment]
When I visit "localhost/admin",  got :

2019/05/31 20:11:50 Finish [GET] /admin Took 0.17ms
2019/05/31 20:11:50 http: panic serving [::1]:49230: runtime error: invalid memory address or nil pointer dereference
goroutine 18 [running]:
net/http.(*conn).serve.func1(0xc00045a000)
	/home/decker/app/go/go/src/net/http/server.go:1769 +0x139
panic(0x9e6f00, 0x10f8050)
	/home/decker/app/go/go/src/runtime/panic.go:522 +0x1b5
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/home/decker/app/go/go/src/html/template/template.go:95 +0x2e
html/template.(*Template).Execute(0x0, 0xb57240, 0xc000472000, 0xa6c5c0, 0xc000476000, 0x1, 0xc0004c4030)
	/home/decker/app/go/go/src/html/template/template.go:119 +0x2f
github.com/qor/admin.(*Context).Execute(0xc000476000, 0xa73e02, 0x9, 0x0, 0x0)
	/home/decker/project/go/pkg/mod/github.com/qor/admin@v0.0.0-20190525133731-6329506ec305/context.go:227 +0x22c
github.com/qor/admin.(*Controller).Dashboard(...)
	/home/decker/project/go/pkg/mod/github.com/qor/admin@v0.0.0-20190525133731-6329506ec305/controller.go:28
github.com/qor/admin.(*Admin).NewServeMux.func2(0xc000476000, 0xc000404560)
	/home/decker/project/go/pkg/mod/github.com/qor/admin@v0.0.0-20190525133731-6329506ec305/route.go:176 +0x202
github.com/qor/admin.Middleware.Next(...)
	/home/decker/project/go/pkg/mod/github.com/qor/admin@v0.0.0-20190525133731-6329506ec305/route.go:37
github.com/qor/admin.(*Admin).NewServeMux.func1(0xc000476000, 0xc000404540)
	/home/decker/project/go/pkg/mod/github.com/qor/admin@v0.0.0-20190525133731-6329506ec305/route.go:166 +0x119
github.com/qor/admin.Middleware.Next(...)
	/home/decker/project/go/pkg/mod/github.com/qor/admin@v0.0.0-20190525133731-6329506ec305/route.go:37
github.com/qor/admin.Admin.registerCompositePrimaryKeyCallback.func1(0xc000476000, 0xc0003ab3e0)
	/home/decker/project/go/pkg/mod/github.com/qor/admin@v0.0.0-20190525133731-6329506ec305/composite_primary_key_callback.go:27 +0x251
github.com/qor/admin.(*serveMux).ServeHTTP(0xc0003a86f8, 0xb60ae0, 0xc000472000, 0xc000464000)
	/home/decker/project/go/pkg/mod/github.com/qor/admin@v0.0.0-20190525133731-6329506ec305/route.go:267 +0x52c
net/http.(*ServeMux).ServeHTTP(0xc0003797c0, 0xb60ae0, 0xc000472000, 0xc000464000)
	/home/decker/app/go/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0003f7110, 0xb60ae0, 0xc000472000, 0xc000464000)
	/home/decker/app/go/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00045a000, 0xb61ca0, 0xc000460040)
	/home/decker/app/go/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/home/decker/app/go/go/src/net/http/server.go:2884 +0x2f4

**Comment by lutfuahmet** [comment]
@decker502 there is some issue with new go module with html template file.

first run this command on your folder.

https://github.com/nomad-software/vend

then copy all view files from vendor/github.com/qor/admin to yourdirectory/app/views/qor.

because go module commands does not copy non go files(like .tmpl or .html files).

**Comment by bubuzzz** [comment]
so ? what to do now ? I got the issue immediately for the first page of the document

**Comment by bubuzzz** [comment]
sorry, i haven't read the closed issue carefully. it is solved in here https://github.com/qor/qor/issues/240
