### ISSUE TITLE
Need help for using qor in heroku

### ISSUE THREAD

**Issue by txgo** [qor/qor#60]
May be it's not issue related to qor.

I set up a mini project [qshop](https://github.com/xi3/qshop) for learning qor. 

It worked fine locally(PORT (8080) and  DATABASE_URL (postgres://username:password@localhost:5432/qshop) ENV variable must be set).

After built successfully, the index page works, but "/admin" page failed in heroku deploy. (heroku-postgre used for database, database table AutoMigrate correctly) 

the error msgs are:

```

Aug 01 17:55:37 qshop heroku/router:  at=error code=H13 desc="Connection closed without response" method=GET path="/admin" host=qshop.herokuapp.com request_id=aef1d2d7-16d6-47e6-909a-acd26ee0ccf3 fwd="118.186.147.12" dyno=web.1 connect=1ms service=2ms status=503 bytes=0 
Aug 01 17:55:37 qshop app/web.1:  Start [GET] /admin 
Aug 01 17:55:37 qshop app/web.1:  Finish [GET] /admin Took 0.29ms 
Aug 01 17:55:37 qshop app/web.1:  http: panic serving 10.111.188.147:38894: runtime error: invalid memory address or nil pointer dereference 
Aug 01 17:55:37 qshop app/web.1:  goroutine 9 [running]: 
Aug 01 17:55:37 qshop app/web.1:  net/http.func·011() 
Aug 01 17:55:37 qshop app/web.1:  	/usr/local/go/src/net/http/server.go:1130 +0xbb 
Aug 01 17:55:37 qshop app/web.1:  html/template.(*Template).escape(0xc208189d40, 0x0, 0x0) 
Aug 01 17:55:37 qshop app/web.1:  	/usr/local/go/src/html/template/template.go:59 +0xe4 
Aug 01 17:55:37 qshop app/web.1:  html/template.(*Template).Execute(0xc208189d40, 0x7fa2aa9a2548, 0xc2080de1e0, 0x984da0, 0xc20817c300, 0x0, 0x0) 
Aug 01 17:55:37 qshop app/web.1:  	/usr/local/go/src/html/template/template.go:75 +0x3d 
Aug 01 17:55:37 qshop app/web.1:  github.com/xi3/qshop/Godeps/_workspace/src/github.com/qor/qor/admin.(*Context).Execute(0xc20817c300, 0x9c97f0, 0x9, 0x0, 0x0) 
Aug 01 17:55:37 qshop app/web.1:  	/tmp/build_16c7e847f933ac62773f9f4a88a3ac8a/xi3-qshop-6e506e2/.heroku/go/src/github.com/xi3/qshop/Godeps/_workspace/src/github.com/qor/qor/admin/context.go:138 +0x536 
Aug 01 17:55:37 qshop app/web.1:  github.com/xi3/qshop/Godeps/_workspace/src/github.com/qor/qor/admin.(*controller).Dashboard(0xc20802c838, 0xc20817c300) 
Aug 01 17:55:37 qshop app/web.1:  	/tmp/build_16c7e847f933ac62773f9f4a88a3ac8a/xi3-qshop-6e506e2/.heroku/go/src/github.com/xi3/qshop/Godeps/_workspace/src/github.com/qor/qor/admin/controller.go:45 +0x4f 
Aug 01 17:55:37 qshop app/web.1:  github.com/xi3/qshop/Godeps/_workspace/src/github.com/qor/qor/admin.*controller.Dashboard·fm(0xc20817c300) 
Aug 01 17:55:37 qshop app/web.1:  	/tmp/build_16c7e847f933ac62773f9f4a88a3ac8a/xi3-qshop-6e506e2/.heroku/go/src/github.com/xi3/qshop/Godeps/_workspace/src/github.com/qor/qor/admin/route.go:79 +0x31 
Aug 01 17:55:37 qshop app/web.1:  github.com/xi3/qshop/Godeps/_workspace/src/github.com/qor/qor/admin.func·035(0xc20817c300, 0xc208180d00) 
Aug 01 17:55:37 qshop app/web.1:  	/tmp/build_16c7e847f933ac62773f9f4a88a3ac8a/xi3-qshop-6e506e2/.heroku/go/src/github.com/xi3/qshop/Godeps/_workspace/src/github.com/qor/qor/admin/route.go:145 +0x5d7 
Aug 01 17:55:37 qshop app/web.1:  github.com/xi3/qshop/Godeps/_workspace/src/github.com/qor/qor/admin.(*Admin).ServeHTTP(0xc2080f25b0, 0x7fa2aa9a24e8, 0xc2080de1e0, 0xc208033d40) 
Aug 01 17:55:37 qshop app/web.1:  	/tmp/build_16c7e847f933ac62773f9f4a88a3ac8a/xi3-qshop-6e506e2/.heroku/go/src/github.com/xi3/qshop/Godeps/_workspace/src/github.com/qor/qor/admin/route.go:197 +0x541 
Aug 01 17:55:37 qshop app/web.1:  net/http.(*ServeMux).ServeHTTP(0xc208189350, 0x7fa2aa9a24e8, 0xc2080de1e0, 0xc208033d40) 
Aug 01 17:55:37 qshop app/web.1:  	/usr/local/go/src/net/http/server.go:1541 +0x17d 
Aug 01 17:55:37 qshop app/web.1:  net/http.serverHandler.ServeHTTP(0xc208194600, 0x7fa2aa9a24e8, 0xc2080de1e0, 0xc208033d40) 
Aug 01 17:55:37 qshop app/web.1:  	/usr/local/go/src/net/http/server.go:1703 +0x19a 
Aug 01 17:55:37 qshop app/web.1:  net/http.(*conn).serve(0xc2080f1c20) 
Aug 01 17:55:37 qshop app/web.1:  	/usr/local/go/src/net/http/server.go:1204 +0xb57 
Aug 01 17:55:37 qshop app/web.1:  created by net/http.(*Server).Serve 
Aug 01 17:55:37 qshop app/web.1:  	/usr/local/go/src/net/http/server.go:1751 +0x35e 

```

Thanks.

**Comment by jinzhu** [comment]
Could you please update gorm and qor, with latest gorm, it should throw the db connection error when initalize the application.

**Comment by neversun** [comment]
Using the latest gorm and qor packages. Server is running fine for everything else (API, DB).

Having the exact same error: Running locally on `localhost:3000` works fine, but crashes on heroku AND locally with `ip:80`.

Here the error log:
```
2016-04-06T09:44:34.510782+00:00 app[web.1]: 2016/04/06 09:44:34 http: panic serving 10.93.192.30:26481: runtime error: invalid memory address or nil pointer dereference
2016-04-06T09:44:34.510783+00:00 app[web.1]: goroutine 19980 [running]:
2016-04-06T09:44:34.510783+00:00 app[web.1]: net/http.(*conn).serve.func1(0xc826e64000, 0x7fc7c0162138, 0xc825b58000)
2016-04-06T09:44:34.510784+00:00 app[web.1]: 	/usr/local/go/src/net/http/server.go:1287 +0xb5
2016-04-06T09:44:34.510785+00:00 app[web.1]: html/template.(*Template).escape(0x0, 0x0, 0x0)
2016-04-06T09:44:34.510786+00:00 app[web.1]: 	/usr/local/go/src/html/template/template.go:79 +0x3c
2016-04-06T09:44:34.510787+00:00 app[web.1]: html/template.(*Template).Execute(0x0, 0x7fc7c0181558, 0xc826e64b00, 0xa14000, 0xc8274220e0, 0x0, 0x0)
2016-04-06T09:44:34.510787+00:00 app[web.1]: 	/usr/local/go/src/html/template/template.go:101 +0x34
2016-04-06T09:44:34.510789+00:00 app[web.1]: github.com/company/company2_app_server/Godeps/_workspace/src/github.com/qor/admin.(*Context).Execute(0xc8274220e0, 0xa2e1e0, 0x9, 0x0, 0x0)
2016-04-06T09:44:34.510791+00:00 app[web.1]: 	/tmp/build_cc8f784b5036d93af6d9dcc6465f1fec/company-company2_app_server-6a4758564421a037b3c6aea5462ebbe75688fe50/.heroku/go/src/github.com/company/company2_app_server/Godeps/_workspace/src/github.com/qor/admin/context.go:195 +0xcd5
2016-04-06T09:44:34.510792+00:00 app[web.1]: github.com/company/company2_app_server/Godeps/_workspace/src/github.com/qor/admin.(*controller).Dashboard(0xc82053e9e0, 0xc8274220e0)
2016-04-06T09:44:34.510792+00:00 app[web.1]: 	/tmp/build_cc8f784b5036d93af6d9dcc6465f1fec/company-company2_app_server-6a4758564421a037b3c6aea5462ebbe75688fe50/.heroku/go/src/github.com/company/company2_app_server/Godeps/_workspace/src/github.com/qor/admin/controller.go:21 +0x42
2016-04-06T09:44:34.510793+00:00 app[web.1]: github.com/company/company2_app_server/Godeps/_workspace/src/github.com/qor/admin.(*controller).Dashboard-fm(0xc8274220e0)
2016-04-06T09:44:34.510794+00:00 app[web.1]: 	/tmp/build_cc8f784b5036d93af6d9dcc6465f1fec/company-company2_app_server-6a4758564421a037b3c6aea5462ebbe75688fe50/.heroku/go/src/github.com/company/company2_app_server/Godeps/_workspace/src/github.com/qor/admin/route.go:106 +0x2a
2016-04-06T09:44:34.510795+00:00 app[web.1]: github.com/company/company2_app_server/Godeps/_workspace/src/github.com/qor/admin.(*Admin).compile.func2(0xc8274220e0, 0xc82000ba80)
2016-04-06T09:44:34.510795+00:00 app[web.1]: 	/tmp/build_cc8f784b5036d93af6d9dcc6465f1fec/company-company2_app_server-6a4758564421a037b3c6aea5462ebbe75688fe50/.heroku/go/src/github.com/company/company2_app_server/Godeps/_workspace/src/github.com/qor/admin/route.go:324 +0x928
2016-04-06T09:44:34.510797+00:00 app[web.1]: github.com/company/company2_app_server/Godeps/_workspace/src/github.com/qor/admin.Middleware.Next(0xa2e0b0, 0xa, 0xc8201cc070, 0xc82000ba80, 0xc8274220e0)
2016-04-06T09:44:34.510836+00:00 app[web.1]: 	/tmp/build_cc8f784b5036d93af6d9dcc6465f1fec/company-company2_app_server-6a4758564421a037b3c6aea5462ebbe75688fe50/.heroku/go/src/github.com/company/company2_app_server/Godeps/_workspace/src/github.com/qor/admin/route.go:35 +0x36
2016-04-06T09:44:34.510846+00:00 app[web.1]: github.com/company/company2_app_server/Godeps/_workspace/src/github.com/qor/admin.(*Admin).compile.func1(0xc8274220e0, 0xc82000ba60)
2016-04-06T09:44:34.510847+00:00 app[web.1]: 	/tmp/build_cc8f784b5036d93af6d9dcc6465f1fec/company-company2_app_server-6a4758564421a037b3c6aea5462ebbe75688fe50/.heroku/go/src/github.com/company/company2_app_server/Godeps/_workspace/src/github.com/qor/admin/route.go:294 +0xbc
2016-04-06T09:44:34.510848+00:00 app[web.1]: github.com/company/company2_app_server/Godeps/_workspace/src/github.com/qor/admin.(*Admin).ServeHTTP(0xc8205195e0, 0x7fc7c016e5f8, 0xc826e64b00, 0xc8267f0000)
2016-04-06T09:44:34.510848+00:00 app[web.1]: 	/tmp/build_cc8f784b5036d93af6d9dcc6465f1fec/company-company2_app_server-6a4758564421a037b3c6aea5462ebbe75688fe50/.heroku/go/src/github.com/company/company2_app_server/Godeps/_workspace/src/github.com/qor/admin/route.go:370 +0x726
2016-04-06T09:44:34.510849+00:00 app[web.1]: net/http.(*ServeMux).ServeHTTP(0xc8205276e0, 0x7fc7c016e5f8, 0xc826e64b00, 0xc8267f0000)
2016-04-06T09:44:34.510849+00:00 app[web.1]: 	/usr/local/go/src/net/http/server.go:1699 +0x17d
2016-04-06T09:44:34.510850+00:00 app[web.1]: github.com/company/company2_app_server/Godeps/_workspace/src/github.com/gorilla/mux.(*Router).ServeHTTP(0xc820015310, 0x7fc7c016e5f8, 0xc826e64b00, 0xc8267f0000)
2016-04-06T09:44:34.510851+00:00 app[web.1]: 	/tmp/build_cc8f784b5036d93af6d9dcc6465f1fec/company-company2_app_server-6a4758564421a037b3c6aea5462ebbe75688fe50/.heroku/go/src/github.com/company/company2_app_server/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:103 +0x270
2016-04-06T09:44:34.510852+00:00 app[web.1]: net/http.serverHandler.ServeHTTP(0xc820a05da0, 0x7fc7c016e5f8, 0xc826e64b00, 0xc8267f0000)
2016-04-06T09:44:34.510852+00:00 app[web.1]: 	/usr/local/go/src/net/http/server.go:1862 +0x19e
2016-04-06T09:44:34.510853+00:00 app[web.1]: net/http.(*conn).serve(0xc826e64000)
2016-04-06T09:44:34.510853+00:00 app[web.1]: 	/usr/local/go/src/net/http/server.go:1361 +0xbee
2016-04-06T09:44:34.510854+00:00 app[web.1]: created by net/http.(*Server).Serve
2016-04-06T09:44:34.510855+00:00 app[web.1]: 	/usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by jinzhu** [comment]
@neversun maybe you haven't push views of qor to the server?

**Comment by neversun** [comment]
Found the problem. It happens because qor is looking within the $GOPATH for it's templates ( `$GOPATH/src/github.com/qor/admin/views/`).

We solved this by copying the views folder contents to `$PROJECT/app/views/qor`.
