### ISSUE TITLE
Publish relationship empty rows in Postgres

### ISSUE THREAD

**Issue by lei-cao** [qor/qor#61]
In the `qor-example` when publish a book, https://github.com/qor/qor-example#publish---edit-first-then-push-to-production-db

While using `postgres` database It returns empty rows here
https://github.com/qor/qor/blob/master/publish/resolver.go#L201

But it woks fine in `mysql`

And it will panic:
```
(/Users/leicao/programming/go/src/github.com/qor/qor/publish/resolver.go:201)
[2015-08-02 17:38:38]  [1.63ms]  SELECT * FROM book_authors_draft
17:38:38 app         | Finish [POST] /admin/publishes Took 79.52ms
17:38:38 app         | http: panic serving [::1]:61560: runtime error: invalid memory address or nil pointer dereference
goroutine 230 [running]:
net/http.func·011()
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1130 +0xbb
database/sql.(*Rows).Columns(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/database/sql/sql.go:1613 +0x5e
github.com/qor/qor/publish.(*resolver).Publish(0xc20824b5f0, 0x0, 0x0)
	/Users/leicao/programming/go/src/github.com/qor/qor/publish/resolver.go:202 +0x210b
github.com/qor/qor/publish.Publish.Publish(0xc2082c0320, 0xc208269900, 0x1, 0x1)
	/Users/leicao/programming/go/src/github.com/qor/qor/publish/publish.go:154 +0x54
github.com/qor/qor/publish.(*publishController).PublishOrDiscard(0xc20804c0c8, 0xc20820e2a0)
	/Users/leicao/programming/go/src/github.com/qor/qor/publish/controller.go:80 +0xb96
github.com/qor/qor/publish.*publishController.PublishOrDiscard·fm(0xc20820e2a0)
	/Users/leicao/programming/go/src/github.com/qor/qor/publish/controller.go:102 +0x31
github.com/qor/qor/admin.func·035(0xc20820e2a0, 0xc2081ab440)
	/Users/leicao/programming/go/src/github.com/qor/qor/admin/route.go:145 +0x5d7
github.com/qor/qor/admin.Middleware.Next(0x7e9d20, 0xc2081ab440, 0xc20820e2a0)
	/Users/leicao/programming/go/src/github.com/qor/qor/admin/route.go:47 +0x3c
github.com/qor/qor/l10n.func·005(0xc20820e2a0, 0xc2081aae90)
	/Users/leicao/programming/go/src/github.com/qor/qor/l10n/l10n.go:195 +0x10a
github.com/qor/qor/admin.(*Admin).ServeHTTP(0xc20805d5e0, 0xad5e38, 0xc2082e03c0, 0xc2082fc000)
	/Users/leicao/programming/go/src/github.com/qor/qor/admin/route.go:197 +0x541
net/http.(*ServeMux).ServeHTTP(0xc2081580c0, 0xad5e38, 0xc2082e03c0, 0xc2082fc000)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc20808ed20, 0xad5e38, 0xc2082e03c0, 0xc2082fc000)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2082e0000)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1751 +0x35e
17:38:38 app         | Start [POST] /admin/publishes
17:38:38 app         |
```

**Comment by jinzhu** [comment]
Hi @lei-cao 

Them problem should be fixed, thank you for your report.
